# Generated by Django 5.0.6 on 2024-07-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="favorite_games",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="fans", to="game_store.game"
            ),
        ),
    ]
